name: Build ws-scrcpy Standalone

on:
  workflow_dispatch: # Memungkinkan kita klik tombol "Run workflow" manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ws-scrcpy Repository
        run: git clone https://github.com/NetrisTV/ws-scrcpy.git .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Versi stabil

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend Client
        run: npm run build

      - name: Package Standalone File
        run: |
          mkdir build-output
          # Pindahkan semua file yang dibutuhkan ke folder output
          cp -r dist node_modules src public index.js package.json build-output/
          cd build-output
          tar -czf ../ws-scrcpy-mido.tar.gz .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ws-scrcpy-mido-build
          path: ws-scrcpy-mido.tar.gz
